### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by de-conf** [AhmNouira/IoT_Platform_Flask#2]
I want to learn this project, but I am following your readme tutorial, and the following error occurred after running it, I hope to provide guidance, thank you
```
 sudo flask run --debugger
```
```
* Serving Flask app "main.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/bin/flask", line 33, in <module>
    sys.exit(load_entry_point('Flask==1.1.2', 'console_scripts', 'flask')())
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 305, in __init__
    self._load_unlocked()
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/albert/code/IoT_Platform_Flask/main.py", line 1, in <module>
    from app import App
  File "/home/albert/code/IoT_Platform_Flask/app/__init__.py", line 28, in <module>
    from app import mqtt
  File "/home/albert/code/IoT_Platform_Flask/app/mqtt.py", line 9, in <module>
    mqtt = Mqtt(App)
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 104, in __init__
    self.init_app(app)
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 183, in init_app
    self._connect()
  File "/usr/lib/python3.9/site-packages/flask_mqtt/__init__.py", line 209, in _connect
    res = self.client.connect(
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by de-conf** [comment]
Solved it,
Install  ` mosquitto ` and ` sudo systemctl start mosquitto.service `

**Comment by de-conf** [comment]
new question:
It seems that there is no database file, after the web page is opened

**Comment by de-conf** [comment]
slove it. Due to the upgrade of alembic version, need to re-execute ` alembic init `
And copy ` versions/76fecaafae74_.py `
and ` alembic upgrade 76fecaafae74 `
this is a good project!!
